[package]
name = "manen"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
comfy-table = "7.1.4"
mlua = { version = "0.10.5", features = ["lua54", "vendored", "anyhow"] }
reedline = "0.40.0"
